= Scripts

Various scripts to get me up and running with development:

* `build.sh` goes to the project root and is main script for GitLab (or other) CI/CD.
* `cicd` directory can be moved as-is.
* `global-tools` directory can be used as a seed for a directory referenced
by environment variable `TOOLS_HOME`.
It's highly recommended to set this explicitly, otherwise it defaults to `$HOME/tools`.

== Java installation

Script `setenv.sh` should be sourced (run in the current shell) to set the environment:
----
. cicd/setenv.sh
----

It sets JDK, that is `JAVA_HOME` variable and prepends `PATH` with the new `JAVA_HOME/bin`.

It can be called with other JDK version like:
----
. cicd/setenv.sh zulujdk-8u202
----

This installs JDK based on definition file `$TOOLS_HOME/java/defs/$1-def.sh`,
where `$1` is the argument (`zulujdk-8u202` in our case).
These definition files can be managed globally, like in `global-tools/java/defs` directory here.
The point is to allow reliable download and unzip/install of a precise tool version anytime.
Download URL can change (and will be redefined), but checksum should be the same (although
archive format can technically change, but it's unlikely).

== Definition files

[IMPORTANT]
====
It's important to settle on variable names used in definition files, because if they change,
all the names ever used have to be set by future definition scripts.

For more general approach I prefer `ARCHIVE_URL` instead of more specific `ARCHIVE_URL`
I used previously.
With this approach it's possible to use common functions/snippets for archive retrieval
and unpacking.
====

TODO

----
# extracting tar.gz/tgz
ARCHIVE_UNPACK_APP="tar xzvf"

# MD5 for Mac
ARCHIVE_SUM_APP="md5 -r"
----

== What about other tools?

Currently `setenv.sh` and `install-tolls.sh` takes care of JDK only - this is not enough.
It would be nice to support Node/Npm and other tools, but then a single version argument is
not sufficient.
Perhaps there should be all-in-one `setenv.sh` without any arguments and smaller `setenv-java.sh`,
`setenv-node.sh`, etc., for other tools or toolsets.
E.g. Node/Npm can be managed together, but there is no reason to tie it to Java version.
That should be set on the project level as needed.

== Enforcing Java version in `build.gradle`

----
ext.jdkVersion = System.properties.'java.vm.name' + ', ' +
	System.properties.'java.vm.version' + ', ' + System.properties.'java.vendor.version'

if (requiredJdkVersion) {
	// If required version is followed by some "builder" suffix, like -debian..., it's OK
	if (!jdkVersion.startsWith(requiredJdkVersion)) {
		ant.fail("Current  JDK version: $jdkVersion\n" +
			"Required JDK version: $requiredJdkVersion\n" +
			"- To ignore this remove 'requiredJdkVersion' property, e.g. use CLI option '-PrequiredJdkVersion'.\n" +
			"- If run from interactive shell, perhaps set environment with: . env/setenv.sh\n" +
			"  . cicd/setenv.sh also installs the missing tools.\n" +
			"- If run from IDE, set projects JDK to required version.")
	}
} else {
	logger.warn "WARNING: JDK version not enforced! Use 'requiredJdkVersion' if required."
}
----
