= OBS Studio Recording

== Video setup

Section: *Setting | Output | Recording*

Recording format: *mkv* - while not easily digested, it's safe when recording crashes.
It is easy to copy streams to MP4 or other containers later using `ffmpeg`.

Audio Track: select first three.

We will use first for the mixed audio, second for the desktop audio only and third for the microphone.

Encoder: *x264* - this one supports rate control via *CRF* which we want to use.
No rescaling needed - we mostly go for 1080p video.

Rate control *CRF* set to *21* and CPU Usage Preset *veryfast*.
This seems to work well enough, the final video can have wide range of bitrates, e.g. UT2004 was around 15Mbps,
but slower game or recording application tutorials can have much lower bitrates.
With lower CRF values (higher quality) and slower CPU presets the video could have jitter,
but this may also depend on background processes.

TODO:
priority above normal

== Audio setup

TODO

== Processing the video

Use the following script:

----
#!/bin/bash
# Takes MKV from OBS with audio tracks 1=mix, 2=desktop-only, 3=mic-only.
# Result from X.mkv is:
# - X.mp4 - video with audio track 1
# - X-desktop.m4a - desktop audio (unprocessed) only
# - X-mic.m4a - microphone audio (unprocessed) only
# All streams (video and audio) are copied from original without changes.
# M4A container is used for audio to allow seeking in AAC stream. MP4 works too, it's around 26B longer.

# set -e is not here to allow [N] answer for ffmpeg overwrite and still go on
set -u

BASE_NAME="${1%.*}"

#ffmpeg.exe -i "$1" -c:v copy -c:a copy "$BASE_NAME".mp4
ffmpeg.exe -i "$1" -map 0:2 -c:a copy -vn "$BASE_NAME"-desktop.m4a
ffmpeg.exe -i "$1" -map 0:3 -c:a copy -vn "$BASE_NAME"-mic.m4a
----

It will create MP4 with audio 1 (mix of PC and mic sound) and 2 more M4A files with separated audio.
Strangely enough, M4A files are smaller than raw AAC - and enable seeking in players like foobar2000.

== Notes

* multi-track audio recording
* ffmpeg for processing

Scene-follow the screen, absolute coordinates, WinSpy: https://youtu.be/ufOFe1EGCHg

MVK multi audio track to:

* MP4 with audio 1 (mix), `-c:v libx264` is implied in this case, `-crf X` is optional:
+
----
ffmpeg.exe -i 2020-06-03_00-06-40.mkv -c:a copy -crf 23 out.mp4`
----

* separate audio 2 (or 3 in this example) with transcoding to MP3:
+
----
ffmpeg.exe -i 2020-06-03_00-06-40.mkv -map 0:3 -vn out3.mp3
----

Script above uses copy-only for both video and audio, which is quite fast, but does not compress the video.
Choosing `mp4` output not only changes the container, but also transcodes the video to (mostly) a smaller one,
unless option `-c:v copy` is used.

== Quality comparison

This table shows file sizes and bitrate for a 30s snippet of Halo gameplay:

|===
| CRF | file size (KB) | kbps video/audio | Notes

| 21 | 29,932 | 8175/160 | Cut with `-c:v copy`, black at the start til the first I-frame (I guess).
CRF 21 is set in OBS (as stated above).
| 20 | 32,491 | 8865/128 | Basic transcode, works from the start even with `-ss` switch. Both A+V is transcoded.
Probably doesn't make sense to go for higher CRF than the source, only shown here to see the size/bitrate growth.
| 23 | 23,963 | 6538/128 | This is the default CRF if none is stated for MP4.
| 25 | 19,112 | 5215/128 | Still usable, small artifacts around contrast UI components.
| 30 | 11,245 | 3068/128 | Surprisingly, still usable, less contrast around text/UI.
Can be a reasonable tradeoff considering massive file size savings.
|===
