# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"
  config.vm.network :private_network, ip: "192.168.10.2"

  # enable NFS - will not work on Windows anyway!
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # enable usb - important if we want to use UI, otherwise mouse/keyboard is not working
  config.vm.provider "virtualbox" do |vb|
    # VM Customizations go here
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
  end
end
