# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "ubuntu-docker"
    # better to have more RAM than default 1GB (e.g. Java builds, etc.)
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    # based on: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

    # suppresses some warnings about stdin/out, see also https://serverfault.com/a/670688/302310
    export DEBIAN_FRONTEND=noninteractive
    # other warnings are still there though (preconfigure, apt-key...)

    sudo apt-get update
    sudo apt-get install -y apt-transport-https \
      ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce

    # user vagrant can use docker command
    sudo usermod -aG docker vagrant
  SHELL
end
