# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.7"

  # Sonar ports
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # Sonar needs more memory, ElasticSearch in particular
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
