= GitLab runner installation

== System preparation

=== Proxy

Avoid the need for proxy as much as you can, it causes tons of problems:

* Many systems have to be set separately (`http(s)_proxy` is not enough).
* Building docker images is pain.

To set the proxy, if needed:
----
# cat /etc/environment
http_proxy="http://proxy-host:8080/"
https_proxy="http://proxy-host:8080/"

# grep proxy /etc/yum.conf
proxy=http://proxy-host:8080/
----

Yum may not need the settings, probably uses environment settings.

Proxy may need to be set also in `/etc/profile` for `gitlab-runner` user (it doesn't use
`/etc/enviroment` by default).
Without this GitLab runner will not be able to download tools using curl/wget (e.g. JDK).
----
# cat /etc/profile
http_proxy="http://proxy-host:8080/"
https_proxy="http://proxy-host:8080/"
----

=== Hosts, resolving

Add short hostname into `/etc/hosts`, for convenience.
----
# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 gitlab-ci1
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 gitlab-ci1

172.16.15.89 gitlab-ci1.full.name
----

`/etc/hostname` is typically set with FQDN of the server.

Check DNS settings from different server and if needed ask for changes.


== GitLab Runner getting up and running

Follow: https://docs.gitlab.com/runner/

=== Installation

Starting from: https://docs.gitlab.com/runner/install/linux-repository.html#installing-the-runner

----
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash
sudo yum install gitlab-runner
----

Upgrade is documented there if needed.

=== Registration

Docs: https://docs.gitlab.com/runner/register/index.html

New runner is registered with:
----
sudo gitlab-runner register
----

Token for Shared Runner must be generated by GitLab admin (project runner can also be used).

* Runner name is set to: `shared-runner-gitlab-ci1`
* Executor is: `shell` (other options are available, this one is most straightforward)

=== Running more jobs at once

In `/etc/gitlab-runner/config.toml` set `concurrent` (by default 1):
----
concurrent = 2
----

Parallel jobs use different directories `$HOME/builds/RANDOM-NUMBER/{0,1}`, this is OK.
Feature request to avoid parallel jobs on a single project: https://gitlab.com/gitlab-org/gitlab-ce/issues/18224


== Setting up the build environment

=== Gradle settings: Proxy and corporate repository

Gradle settings are made under `gitlab-runner` user in his `$HOME/.gradle/gradle.properties`.
This can be pre-created even before running the first Gradle build.
----
# proxy setup, Gradle doesn't use system variables
systemProp.http.proxyHost=proxy-host
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=proxy-host
systemProp.https.proxyPort=8080

# corporate libs, etc.
ourMavenAggregationUrl=http://maven.our/content/repositories/aggregation
ourMavenAggregationUser=gitlab-robot
ourMavenAggregationPassword=password
----

Later we can add repository for publishing artifact.
I recommend semantic name, e.g. not `someNexusSomething`, but `companyMavenReleases*` with
`Url/User/Password` all set for each (even if the same).
Other examples are `companyProjectBinary*` for raw type repository (or use `Raw` instead of
`Binary`) or `companyProjectDocker*` for Docker images.

=== Maven settings

Similar to Gradle settings, just use `$HOME/.m2/settings.xml` (including proxy if needed).

If using proxy and Maven Wrapper `.m2/settings.xml` is not enough, better add the following
into `~/.bashrc`:
----
export MAVEN_OPTS="-Dhttp.proxyHost=proxy-host -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy-host -Dhttps.proxyPort=8080"
----

=== Remote SSH access to various servers (for deployment)

This is security hole, obviously, use other methods if available.
But we can just generate SSH key (using `gitlab-runner` user):
----
ssh-keygen
cat ~/.ssh/id_rsa.pub
----

The just copy/paste the printed public key into `~/.ssh/authorized_keys` on the destination
server/user, e.g.:
----
ssh appuser@some-host
vi .ssh/authorized_keys # and paste it to the end
----

Check it manually the fist time, this way you will also accept the server key, which requires
interaction (without additional options).
