= Handy commands

== Networking

* On Linux, use `ss` instead of `netstat`, e.g. `ss -l` for listen ports.

* Check programs listening on Windows: `netstat -abno | grep -i listen`

* Windows GUI application for network ports/processes: `tcpview` (available via Chocolatey)

== Curl

Curl has many switches, but some are very useful most of the time:

----
curl -fsSkL -C - -o <output-file> <url>
----

* `-f` fail, handy in scripts with `set -eu` to abort them on non-200/300 reply (or other error),
* `-s` silent, doesn't show progress, etc.
* `-S` print error output, even with `-s` (`-f` also fails silently), very important feedback
* `-k` ignores certificate when using TLS (think twice, but often handy in internal networks)
* `-L` follow redirects (HTTP 3xx), like download link taken from a pages that is just redirect
* `-C -` continue/resume, offset is determined automatically
* `-o <output-file>` to save under specific name

To POST JSON from file `some.json` somewhere:
----
curl -fsSk -d @some.json \
  -H "Content-Type: application/json" \
  -H "Other-Header: like API key or what" \
  <url>
----

To POST JSON from stdin (`-d @-`), here using here string with verbose output (`-v`, overrides `-s`):
----
curl -fsSk -d @- http://localhost:8080/some/service -v <<< '{"id":1}'
----

Without header it sends `Accept: */*` which may work for `GET` but typically not for `POST`.

=== Handy Curl aliases for REST

When working more with some JSON/REST API, we may want to define aliases like these:
----
alias POST='curl -fsSk -H "Accept: application/json" -d @-'
alias GET='curl -fsSk -H "Accept: application/json"'
----

Examples of usage:
----
# POST without body with verbose output
POST -v 'http://some.url:port/api/v1/something' <<<''
GET 'http://some.url:port/api/v1/resource'
----

To format JSON we can use https://stedolan.github.io/jq/[jq], which can be downloaded also as
a static binary.

== less

Normally `less` clears the screen after it's quit, which may be annoying if we want to see the content.
To prevent it, we can use `less -X`.
To make this default we can set `LESS` environment variable, e.g. in link:bash-startup-files/.bashrc[`~/.bashrc`].
To make it work even in programs that use `less` as a default pager, we can set `PAGER` variable.

Both can be seen here:

[source,bash]
----
include::bash-startup-files/.bashrc[tag=variables]
----
