= Faster setup of new Windows

== Chocolatey

Start with Chocolatey package system - in *administrative* cmd:

----
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))"
----

All the following commands are with `cmd` syntax (e.g. `"` instead of `'`).
By default, Chocolatey downloads into TEMP directory, which results in repeated downloads, when
you experiment a lot with the same package.
You may point it to a specific directory like this:

----
choco config set cacheLocation "c:\ProgramData\Chocolatey\tmp-cache"
----
Also https://github.com/chocolatey/choco/wiki/How-To-Change-Cache[see here].
As a result you have to take care of the directory and maybe clean it up sometimes.
You can also pack this cache directory and move it elsewhere to do offline installation.
(!) TODO: check how this works, because http://stackoverflow.com/questions/18528919/how-to-install-chocolatey-packages-offline[there is more to it].

To allow packages without checksums (avoiding prompt every time):

----
choco feature enable -n allowEmptyChecksums
----

To find out what is installed using Chocolatey, use `choco list -l` or shortcut `clist -l`.
Without `-l` it prints all available packages.
Using `clist -li` prints also applications that are not installed using Chocolatey, but could have been.
To upgrade all installed tools later we just use `cup -y all` (`all` is a special package keyword).

== Chocolatey packages

We can install and download virtually any other favourite tool:

[NOTE]
Sometimes `cinst` doesn't work as expected, e.g. it reports dependency resolution problems, etc.
It's better to wait a couple of hours (or days if possible), to let this problem go away, it's often
nonessential and transitory (yet annoying).

----
choco install -y open-shell
choco install -y firefox
choco install -y notepad2
choco install -y TotalCommander
choco install -y winmerge
choco install -y rapidee
choco install -y GoogleChrome
choco install -y FoxitReader
choco install -y k-litecodecpackfull
choco install -y foobar2000
choco install -y gimp
choco install -y fsviewer
choco install -y imagemagick
choco install -y exiftool
choco install -y slack
choco install -y obs-studio
choco install -y cpu-z
choco install -y hwmonitor
----

Open Shell (previously Classic Shell) set to Aero, small icons.
OBS Studio is screen capturing software.

Developer's tools mandatory:

----
choco install -y git
choco install -y putty
choco install -y winscp
choco install -y 7zip.commandline
choco install -y unzip
REM choco install -y vim # don't need gvim and vim comes with git
choco install -y tortoisesvn
choco install -y wget
choco install -y jq
choco install -y cloc
choco install -y vscodium
----

Other tools for virtualization and other experiments:

----
choco install -y virtualbox
choco install -y vagrant
REM choco install -y packer
----

Greenshot, first https://superuser.com/a/1239937[disable PrintScreen key in OneDrive] (just press
`PrtSc` and say "No..."):

----
choco install -y greenshot
----

Programming (`ghc` is haskell), in order of general usefulness (`python3` provides `pip`):

----
choco install -y python3
choco install -y ruby
choco install -y StrawberryPerl
choco install -y ghc
----

With Python 3 (and PIP) we can install HTTPie.
This can be done in non-admin shell too, but why not to provide it for everyone.
To avoid the need to reopen the console, we call `refreshenv` first:

----
refreshenv
pip install --upgrade pip setuptools httpie
----

If there are problems with Windows permissions, we may do it just for the user adding `--user`
switch, but then we need to add local scripts to `PATH`.
These are typically in `%APPDATA%\Python\Python38\Scripts` or similar.

The rest (back in admin `cmd`):

----
choco install -y processhacker
choco install -y gpg4win-light
choco install -y openvpn-connect
choco install -y licecap
choco install -y nodejs-lts

REM instal WinPcap in advance manually, seems the chocolatey package is broken
choco install -y wireshark
----

We can install various GnuWin32 packages:

----
choco install -y gnuwin32-coreutils.install
choco install -y gnuwin32-grep.install
choco install -y gnuwin32-sed.install
----

*But instead* we can use existing Git and add `c:\Program Files\Git\usr\bin` and
`c:\Program Files\Git\mingw64\bin` to the `PATH` (especially the first one).

== Installing fonts

Source * Pro fonts by Adobe and many others can now be downloaded from https://fonts.google.com.
The following bash snippet downloads all the fonts of interest and unpacks them.
Execute in some temporary directory:

----
wget -q https://fonts.google.com/download?family=Poppins -O poppins.zip
wget -q https://fonts.google.com/download?family=Raleway -O raleway.zip
wget -q https://fonts.google.com/download?family=Josefin%20Sans -O jozefin-sans.zip
wget -q https://fonts.google.com/download?family=Open%20Sans -O open-sans.zip
wget -q https://fonts.google.com/download?family=Source%20Sans%20Pro -O source-sans-pro.zip
wget -q https://fonts.google.com/download?family=Source%20Serif%20Pro -O source-serif-pro.zip
wget -q https://fonts.google.com/download?family=Source%20Code%20Pro -O source-code-pro.zip
for i in *.zip; do unzip -qo $i; done
----

After that open `TTF` folder, select `*.ttf` files, right-click, install fonts.
Some fonts are "variable" and their "static" counterparts are in sub-folders which can be omitted.

=== Trick with GitHub SVN export

While not useful for fonts if the script above is used this is a neat trick on its own.
SVN can download subdirectory of GitHub project (`--force` needed if directory exists).
Go to some temporary/download directory and:

----
svn export https://github.com/adobe-fonts/source-sans-pro/branches/release/TTF
svn export --force https://github.com/adobe-fonts/source-serif-pro/branches/release/TTF
svn export --force https://github.com/adobe-fonts/source-code-pro/branches/release/TTF
----

After that open `TTF` folder, select all, right-click, install fonts.

== More Windows settings

=== Wallpapers and logon screen

* Right-click on the desktop , Personalize
* *Background* section, *Background* select to *Slideshow* and choose the directory with my wallpapers (perhaps directly from OneDrive?)
* *Lock screen* section, choose a picture and check *Show lock screen background picture on the sign-in screen*.
* *Colors* section, switch off *Transparency effects*.

=== Disable snap assist, autocorrect...

* *Settings* (`Win+I`), *System*, *Multitasking* section, toggle off *When I snap a window...*

* *Settings* (`Win+I`), *Devices*, *Typing* section, toggle off both *Autocorrect/Highlight misspelled...*
(This should, but does not help with Skype autocorrect, not even in versions that don't have other
options to turn it off.
Still better to have it off.)

=== Firefox setup

Most things can be set from `about:config` URL (see parentheses, valid for Firefox 65):

* Toolbar right-click, Customize... add search bar (`browser.search.widget.inNavBar = true`)
* Options:
** Ask to save logins and passwords for websites OFF (`signon.rememberSignons = false`)
** Show search suggestions in address bar results OFF (`browser.urlbar.suggest.searches = false`)
** Restore previous session (`browser.startup.page = 3`)
** Remove Reader view from address bar (`reader.parse-on-load.enabled = false`)
** Disable Firefox automatic start-up (`toolkit.winRegisterApplicationRestart = false`)
* More about:config (NTLM/Windows SSO + certificates):
** `security.enterprise_roots.enabled = true`
** `network.automatic-ntlm-auth.trusted-uris = company.com,hostnames-without-domain`
** `network.negotiate-auth.trusted-uris = ...`

== Various Windows tips/problems

=== Windows Defender folder exclusions

For I/O heavy folders (programming, video, photo) it's possible to turn off Windows Defender.

* *Settings* (`Win+I`), *Update & Security*, *Windows Security* (opens new window),
*Virus & threat protection* on the left, link *Manage settings* in the right section,
then scroll down to *Exclusions*, link *Add or remove exclusions* and add directories like:
** `~/.IntelliJIdea2019.3/system` (Idea asks about it and fixes it anyway)
** `~/.m2` because of massive library caches
** `~/.gradle` ditto
** `/c/work/workspace` programming projects
** `/c/work/video-projects` etc.

In theory the whole `/c/work` could be added, but with binaries under `/c/work/tools` it's perhaps
not a good idea.

=== Setting PATH and other environment variables permanently

`SETX` is the command that should handle it, `/M` tells it to use system environment, not local one.

----
SETX /M JAVA_HOME "c:\Program Files\Java\jdk1.8.0_92"
----

TODO: Is it possible ot use other variable in PATH? How to display unexpanded variable string?

=== Problem: Blurry fonts on dual monitor or in some applications

Set both monitors to the same size of font (typically it is 125% on the notebook and 100% on
external monitor, 125% is rather too much for the monitor, so 100% is better for both).

=== Problem: `Ctrl+Alt+F8` resets monitors

This combo also collides with IDEA. It's used by *Intel HD Graphics Control Panel Service* and
cannot be disabled (unlike other shortcuts of that service). The whole service can be disabled
as http://stackoverflow.com/a/35109007/658826[described here].

=== Git Bash Here in Total Commander

Better yet is to copy `usercmd.ini` and `wincmd.ini` from old computer/backup to a new one (from `AppData\Roaming\GHISLER` directory).

Based on https://virgo47.wordpress.com/2013/05/05/git-bash-here-in-console2-in-total-commander-with-keyboard-shortcut-hotkey/[my blog]
where it is for Console2 - this time for Windows 11 terminal which is actually quite usable.
Setup for user command in Total Commander is (as found in `AppData\Roaming\GHISLER\usercmd.ini`):

----
[em_git_bash_here]
button=C:\Program Files\Git\git-bash.exe
cmd=C:\Users\virgo\AppData\Local\Microsoft\WindowsApps\wt.exe

menu=Git Bash Here
param=-w 0 nt -p "Git Bash" -d "%P%"
----

This counts on existing profile called "Git bash" which should be available automatically with Windows Git.

Then also add this to `wincmd.ini` in the same directory as `usercmd.ini` (both `Alt+B` and `Ctrl+B` launch Git Bash):

----
[Shortcuts]
C+B=em_git_bash_here
A+B=em_git_bash_here
----
